name: master_car_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  fluttertoast: ^8.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_html: ^2.2.1
  http: ^0.13.4
  firebase_messaging: ^11.4.1
  firebase_core: ^1.17.1
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.6.0
  flutter_countdown_timer: ^4.1.0
  date_count_down: ^1.0.2
  url_launcher: ^6.1.3
  provider: ^6.0.3
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_lints: ^2.0.1


flutter_app_name:
  #name: "Master Car"



flutter:
  assets:
    - assets/images/

  fonts:
    - family: GE
      fonts:
        - asset: assets/fonts/GE.ttf
          weight: 100
          style: italic


  uses-material-design: true

